In [19]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Data Generation
===

In [20]:
num_samples, num_features = 10, 5

In [21]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [22]:
print(data)

[[ 0.77132064  0.02075195  0.63364823  0.74880388  0.49850701]
 [ 0.22479665  0.19806286  0.76053071  0.16911084  0.08833981]
 [ 0.68535982  0.95339335  0.00394827  0.51219226  0.81262096]
 [ 0.61252607  0.72175532  0.29187607  0.91777412  0.71457578]
 [ 0.54254437  0.14217005  0.37334076  0.67413362  0.44183317]
 [ 0.43401399  0.61776698  0.51313824  0.65039718  0.60103895]
 [ 0.8052232   0.52164715  0.90864888  0.31923609  0.09045935]
 [ 0.30070006  0.11398436  0.82868133  0.04689632  0.62628715]
 [ 0.54758616  0.819287    0.19894754  0.8568503   0.35165264]
 [ 0.75464769  0.29596171  0.88393648  0.32551164  0.1650159 ]]


In [34]:
def standardize(x):
    x = x / x.max()
    return x

std_data = standardize(data)

In [24]:
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 7.71320643  0.20751949  6.33648235  7.48803883  4.98507012]
 [ 2.24796646  1.98062865  7.60530712  1.69110837  0.88339814]
 [ 6.85359818  9.53393346  0.03948266  5.12192263  8.12620962]
 [ 6.12526067  7.21755317  2.91876068  9.17774123  7.14575783]
 [ 5.42544368  1.42170048  3.7334076   6.74133615  4.41833174]
 [ 4.34013993  6.17766978  5.13138243  6.50397182  6.01038953]
 [ 8.05223197  5.21647152  9.08648881  3.19236089  0.90459349]
 [ 3.00700057  1.13984362  8.28681326  0.46896319  6.26287148]
 [ 5.47586156  8.19286996  1.9894754   8.56850302  3.51652639]
 [ 7.54647692  2.95961707  8.8393648   3.25511638  1.65015898]] 

 [ 5.67871864  4.40478072  5.39669651  5.22090625  4.39033073] 

 [ 1.8880201   3.12269258  2.98104761  2.8105224   2.4648668 ]
